name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22" # specify the Go version you are using

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v $(go list ./... | grep -v 'repositories')

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.out
